### ISSUE TITLE
[suggestion] Validate the structure of JSON files on CI

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-toolbox-json-files#3]
To avoid creating broken files, what do you think about creating a small script which would validate the structure of the JSON files to detect mistakes ?
Then, it would be easy to configure Travis to run this script. This is what we did in https://github.com/FriendsOfPHP/security-advisories for instance. It allows to get much faster feedback about invalid files (and the validator can be enhanced over time to catch more mistakes)

**Comment by tiger-seo** [comment]
+1

**Comment by Haehnchen** [comment]
added a really simple script to valid json files: https://github.com/Haehnchen/idea-php-toolbox-json-files/blob/master/validator.php
